name:                lm
version:             0.1.0.0
github:              "TomJamesGray/lm"
license:             BSD3
author:              "Tom Gray"
maintainer:          "tomg77@protonmail.com"
copyright:           "2020 Tom Gray"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lm#readme>

dependencies:
- base >= 4.7 && < 4.14
- hspec >= 2.7

library:
  source-dirs: src

executables:
  lm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lm

tests:
  lm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lm
